name: SSH Test To G100

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H loginin.g100.cineca.it >> ~/.ssh/known_hosts

    - name: Test SSH connection to G100
      run: |
        ssh -i ~/.ssh/id_ed25519 zqiao000@loginin.g100.cineca.it "echo ✅ GitHub Actions SSH Success"
